wandb_project_name: SemesterProject
logdir: 'results/mnist'
logger: 
  type: base
  endwith: ['@', '#']
model:
  encoder:
    arch: fc_image
    l_hidden: [256, 256, 256, 256, ]
    activation: ['elu', 'elu', 'elu', 'elu', ]
    out_activation: 'linear'
    img_size: [1, 28, 28]
    out_chan_num: 1
  decoder:
    arch: fc_image
    l_hidden: [256, 256, 256, 256, ]
    activation: ['elu', 'elu', 'elu', 'elu', ]
    out_activation: 'linear'
    img_size: [1, 28, 28]
    out_chan_num: 1
  x_dim: 784
  z_dim: 2
data:
  training:
    dataset: MNIST
    root: datasets
    batch_size: 100
    n_workers: 4
    split: training
    shuffle: True
    digits: 'all'
  validation:
    dataset: MNIST
    root: datasets
    batch_size: 100
    n_workers: 4
    split: validation
    shuffle: True
    digits: 'all'
trainer: base
training:
  n_epoch: 100
  optimizer:
    name: 'adam'
    lr: 0.0005
  print_interval: 100
  val_interval: 100
  eval_interval: 1000
  visualize_interval: 1000