device: cpu

seeds: [1, 2, 3]

models: [
    "ae",
    "confae-log",
    "geomae",
    "irae",
]

metrics: ["CN", "voR", "VP"]

datasets: [
    "mnist",
    "zilionis",
    "pbmc",
    # "earth",
    "celegans",
]

METRIC_FOR_MODEL: 
  confae-log: CN
  geomae: VP
  irae: voR
  ae: mse

source: "/local/home/pnazari/workspace/SemesterProject"
output_path: "/local/home/pnazari/workspace/SemesterProject/output"
results_path: "/local/home/pnazari/workspace/SemesterProject/results"
data_path: "/local/home/pnazari/workspace/SemesterProject/datasets"

show: False

type_of_mse: "mse"  # in mse and train_mse

part_of_ae:
  reg: "encoder"
  vis: "encoder"
